repos:
  - repo: https://github.com/psf/black
    rev: 24.8.0  # 최신 안정 버전 (필요시 업데이트)
    hooks:
      - id: black
        language_version: python3
        args: ["--line-length=88"]
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: []
        # flake8 설정은 .flake8 파일에서 관리
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=500"]
